#!/bin/sh

# git mv file name to new subdirectory index.
#
# Example: from "foo.md" to "foo/index.md"
#
# If the file name is already "index.md" then skip it.
#
while read file; do
    file_basename=$(basename "$file")
    if [ "$file_basename" = "index.md" ]; then
        continue
    fi
    new_dirname=${file_basename%.md}
    mkdir -p "$new_dirname"
    git mv "$file_name" "$new_dirname/index.md"
done
